name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  default:
    name: do it lady
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv and setup Python
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.26"
          enable-cache: true

      - name: Run tests with coverage
        run: uv run --group test pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: unittests
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload tests to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: unittests
          fail_ci_if_error: true
          report_type: test_results
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
